// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fGUFQJS4g2CfwxgMXJrtsQ0k6gsQYMc',
    appId: '1:984368302717:web:fa19906b8261b8eb92bf14',
    messagingSenderId: '984368302717',
    projectId: 'jjg-instagram-clone',
    authDomain: 'jjg-instagram-clone.firebaseapp.com',
    storageBucket: 'jjg-instagram-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEsf-Iv0UqZFNL3dHC4jTe3e9oZQmUPA',
    appId: '1:984368302717:android:06a9519e57ef602d92bf14',
    messagingSenderId: '984368302717',
    projectId: 'jjg-instagram-clone',
    storageBucket: 'jjg-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh6CycjhqwK2rLxb0KzvbTh-OehhlhiWo',
    appId: '1:984368302717:ios:3b41191be38c205e92bf14',
    messagingSenderId: '984368302717',
    projectId: 'jjg-instagram-clone',
    storageBucket: 'jjg-instagram-clone.appspot.com',
    iosClientId: '984368302717-81ide4ubiterrnf22r70gqrqttfmgkqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.igcloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh6CycjhqwK2rLxb0KzvbTh-OehhlhiWo',
    appId: '1:984368302717:ios:569adc9076a0ffc892bf14',
    messagingSenderId: '984368302717',
    projectId: 'jjg-instagram-clone',
    storageBucket: 'jjg-instagram-clone.appspot.com',
    iosClientId: '984368302717-svgmj6e9p8gnlmvklam1lvrtjpu4em9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.igcloneFlutter.RunnerTests',
  );
}
